In [6]:
from jhr.codes.espresso.io import QEOutParser

In [7]:
prs = QEOutParser('pw.x')

In [8]:
file = '/home/fes33/Documents/GIK - R&D/Personal - Papers and Reports/--Libraries/abinit/jhr/scripts/study/scf.out'
df = prs.parser.Process(file)

In [9]:
df

,value,unit,description
program_version,v.7.4.1,N/A,Quantum ESPRESSO version
alat,6.275143,Å,Lattice parameter (alat)
volume,247.098904,Å³,Unit cell volume
natoms,5,unitless,Number of atoms per unit cell
natypes,3,unitless,Number of atomic types
nelectrons,20.0,unitless,Number of electrons
bands,14,unitless,Number of Kohn-Sham states (bands)
ecut,68.02849,eV,Kinetic energy cutoff
rhocut,272.113961,eV,Charge density cutoff
econvergence,0.000001,unitless,Electronic convergence threshold
mixing_beta,0.7,unitless,Mixing beta parameter
xc_functional,PBE,N/A,Exchange-correlation functional
a_vector,"[1.0, 0.0, 0.0]",alat units,Lattice vector a
b_vector,"[0.0, 1.0, 0.0]",alat units,Lattice vector b
c_vector,"[0.0, 0.0, 1.0]",alat units,Lattice vector c
atomic_positions,"[[Cs, 3.1375712859083498, 3.1375712859083498, ...",Å,List of atomic species and positions
kpoints,4,unitless,Number of k-points in the Brillouin zone
bnddiagram,"[[-16.81, -16.4046, -16.4046, -16.3551, -15.69...",N/A,Band diagram
Fermi_energy,-0.7879,eV,Fermi level
total_energy,-723.267401,eV,Total energy

In [5]:
df.loc['bands'][0]

14

In [33]:
l = [at[1:] for at in df.loc['atomic_positions'][0]]
l

[[3.1375712859083498, 3.1375712859083498, 3.1375712859083498],
 [0.0, 0.0, 0.0],
 [0.0, 0.0, 3.1375712859083498],
 [0.0, 3.1375712859083498, 0.0],
 [3.1375712859083498, 0.0, 0.0]]

In [18]:
set = {1,2,3}

In [20]:
setb = {3,2,1}

In [21]:
set == setb

True

In [58]:
import re

txt = """        k(   10) = (  -0.5000000  -0.5000000  -0.5000000), wk =   0.0312500
k = 0.0000 0.0000 0.2 ( 55707 PWs)   bands (ev):
-18.1741 -18.1738 -18.1737 -18.1737 -18.1734 -18.1734 -18.1733 -18.1730
   -13.4577 -13.4558 -13.4513 -13.4503 -13.4499 -13.4486 -13.4372 -13.4352
   -13.3825 -13.3820 -13.3819 -13.3819 -13.3819 -13.3810 -13.3810 -13.3810
   -13.3810 -13.3810 -13.3810 -13.3810 -13.3769 -13.3769 -13.3769 -13.3350
   -13.3346 -13.3346 -13.3154 -13.3154 -13.3154 -13.2872 -13.2872 -13.2871"""
x = re.findall("k =.*:", txt)

In [59]:
kpoints = []

for line in lines:
    if 'k =' in line and 'wk =' not in line:
        # Extract the first three floats after "k ="
        floats = re.findall(r'[-+]?\d*\.\d+|\d+', line)
        kpoints.append([float(f) for f in floats[:3]])

# Convert to numpy array
k_array = np.array(kpoints)

print(k_array)

In [61]:
import re
import numpy as np

with open('/home/fes33/Documents/GIK - R&D/Personal - Papers and Reports/--Libraries/abinit/jhr/data/outfiles/scf/pwscf.out', 'r') as f:
    lines = f.readlines()

def _find_kpoints(lines):
    
    kpoints = []

    for line in lines:
        if 'k =' in line and 'wk =' not in line:
            # Extract the first three floats after "k ="
            floats = re.findall(r'[-+]?\d*\.\d+|\d+', line)
            kpoints.append([float(f) for f in floats[:3]])
    k_array = np.array(kpoints)

# Convert to numpy array
k_array = _find_kpoints()
print(k_array)

[[ 0.    0.    0.  ]
 [ 0.    0.    0.25]
 [ 0.    0.   -0.5 ]
 [ 0.    0.25  0.25]
 [ 0.    0.25 -0.5 ]
 [ 0.   -0.5  -0.5 ]
 [ 0.25  0.25  0.25]
 [ 0.25  0.25 -0.5 ]
 [ 0.25 -0.5  -0.5 ]
 [-0.5  -0.5  -0.5 ]]

In [1]:
import numpy as np
import re

from jhr.codes.espresso.io import QEOutParser


file = "/home/fes33/Documents/GIK - R&D/Personal - Papers and Reports/--Libraries/abinit/jhr/data/outfiles/scf/pwscf.out"        

prs = QEOutParser('pw.x', file = file)
df = prs.parser.Process()
array_dict = prs.parser.band_occupancy()


occ =    array_dict['occupancy_array'] 
bands =    array_dict['bands_array'] 

occ = np.where(occ > 0.9, 1, 0)
bocc = bands*occ
bocc.max()

Found 10 occurrences of bands (ev)
Found 10 occurrences of occupation numbers

2.0427

In [2]:
df

,value,unit,description
program_version,v.7.4,N/A,Quantum ESPRESSO version
alat,12.455086,Å,Lattice parameter (alat)
volume,1932.149514,Å³,Unit cell volume
natoms,39,unitless,Number of atoms per unit cell
natypes,3,unitless,Number of atomic types
nelectrons,338.0,unitless,Number of electrons
bands,203,unitless,Number of Kohn-Sham states (bands)
ecut,544.227923,eV,Kinetic energy cutoff
rhocut,4353.823381,eV,Charge density cutoff
econvergence,0.0,unitless,Electronic convergence threshold
mixing_beta,0.4,unitless,Mixing beta parameter
xc_functional,SLA,N/A,Exchange-correlation functional
a_vector,"[1.0, 0.0, 0.0]",alat units,Lattice vector a
b_vector,"[0.0, 1.0, 0.0]",alat units,Lattice vector b
c_vector,"[0.0, 0.0, 1.0]",alat units,Lattice vector c
atomic_positions,"[[Cs, 3.0065706125852496, 3.0065706125852496, ...",Å,List of atomic species and positions
kpoints,10,unitless,Number of k-points in the Brillouin zone
bnddiagram,"[[-18.1742, -18.1738, -18.1738, -18.1738, -18....",N/A,Band diagram
Fermi_energy,3.4611,eV,Fermi level
total_energy,-213526.047981,eV,Total energy

2.0427

In [ ]:
# Use argmax: it returns the first occurrence of True (i.e., 0)
first_zero_indices = zero_mask.argmax(axis=1)

# Handle rows with no zero (argmax will still return 0)
# So we need to mark those rows manually
has_zero = zero_mask.any(axis=1)
first_zero_indices[~has_zero] = -1  # or any other marker like 203

print(first_zero_indices)